# Generated by Django 5.2.1 on 2025-07-16 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Step_Instances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_instance_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("user_id", models.UUIDField(default=uuid.uuid4)),
                ("status", models.CharField(max_length=255)),
                (
                    "step_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.steps",
                        to_field="step_id",
                    ),
                ),
                (
                    "ticket_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tickets.tickets",
                        to_field="ticket_id",
                    ),
                ),
            ],
            options={
                "db_table": "step_instances",
            },
        ),
        migrations.CreateModel(
            name="Instance_Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance_log_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("message", models.CharField(max_length=255)),
                (
                    "transition_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.transitions",
                        to_field="transition_id",
                    ),
                ),
                (
                    "step_instance_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instances.step_instances",
                        to_field="step_instance_id",
                    ),
                ),
            ],
            options={
                "db_table": "instance_logs",
            },
        ),
    ]
