# Generated by Django 5.2.1 on 2025-07-16 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("system_id", models.UUIDField()),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="Workflows",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("workflow_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("category", models.CharField(max_length=255)),
                ("sub_category", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("is_published", models.BooleanField(blank=True, null=True)),
                ("status", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "workflows",
            },
        ),
        migrations.CreateModel(
            name="Steps",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("step_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("instruction", models.TextField(blank=True, null=True)),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.roles",
                        to_field="role_id",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.workflows",
                        to_field="workflow_id",
                    ),
                ),
            ],
            options={
                "db_table": "steps",
            },
        ),
        migrations.CreateModel(
            name="Transitions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("transition_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "from_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_from",
                        to="workflow.steps",
                        to_field="step_id",
                    ),
                ),
                (
                    "to_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_to",
                        to="workflow.steps",
                        to_field="step_id",
                    ),
                ),
            ],
            options={
                "db_table": "transitions",
            },
        ),
    ]
